Repository vikasdo/Book-Recommendation-Analysis, pull requests merged in 2021-03, with the labels that each got.

#46 Gssoc'21 Fixes Bug in Login/Signup System and add form validations
  .github/workflows/codeql-analysis.yml
  .github/workflows/ossar-analysis.yml
  bookstore/client/views.py
  bookstore/templates/client/login.html
  bookstore/templates/client/signup.html
  db.sqlite
Labels: GSSOC21, bug, level 4

#50 added comments
  bookstore/client/views.py
  bookstore/templates/client/login.html
  bookstore/templates/client/signup.html
Labels: GSSOC21, bug, level 4

#62 Contact Page Updated with Header
  bookstore/client/views.py
  bookstore/models.py
  bookstore/static/css/contact.css
  bookstore/templates/client/contact.html
  bookstore/templates/client/header.html
  db.sqlite
Labels: GSSOC21, level 2

#65 show password feature
  bookstore/templates/client/login.html
Labels: GSSOC21, enhancement, level 1
