Repository vikasdo/Book-Recommendation-Analysis, pull requests merged in 2021-04, with the labels that each got.

#72 [Gssoc'21] Fixed the accessibility of contact page to all
  bookstore/client/views.py
  bookstore/static/css/contact.css
  bookstore/templates/client/contact.html
  bookstore/templates/client/contact2.html
  bookstore/templates/client/header.html
  db.sqlite
Labels: GSSOC21, bug, level 1

#79 [Gssoc'21] Added the 404 page and code to handle 404 error
  bookstore/client/views.py
  bookstore/templates/client/404.html
  db.sqlite
Labels: GSSOC21, level1

#82 added author dashboard
  bookstore/client/views.py
  bookstore/templates/client/author_db.html
  bookstore/templates/client/header.html
  db.sqlite
Labels: GSSOC21, level3

#88 [Gssoc'21] Added a confirmation alert after clicking on logout.
  bookstore/templates/client/header.html
Labels: GSSOC21, level0

#93 Activated the Welcome bot
  .github/workflows/greetings.yml
Labels: GSSOC21, level0

#100 Download Contact as csv
  bookstore/client/views.py
  bookstore/templates/adminheader.html
  bookstore/templates/index.html
Labels: GSSOC21, level2

#101 Password Validations in front -End
  bookstore/templates/client/signup.html
Labels: GSSOC21, level2

#103 add contributing.md
  CONTRIBUTING.md
Labels: GSSOC21, level1

#104 Added no.of forks,isues,stars,pr's and licence and repo size
  README.md
Labels: GSSOC21, level1

#107 Download books details as csv
  bookstore/client/views.py
  bookstore/templates/index.html
Labels: GSSOC21, level2
