Repository vikasdo/Book-Recommendation-Analysis, pull requests merged in 2021-05, with the labels that each got.

#109 Update README.md
  README.md
Labels: GSSOC21, level0

#115 Updated Contact Page
  bookstore/templates/client/contact2.html
Labels: GSSOC21, enhancement, level1

#112 Commit
  .idea/.gitignore
  .idea/Book-Recommendation-Analysis.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Toggle button.js
Labels: GSSOC21, enhancement, level1

#116 Updated Sign Up Page
  bookstore/templates/client/signup.html
Labels: GSSOC21, bug, level1

#119 Added Favicon
  bookstore/templates/client/Favicon.png
  bookstore/templates/client/header.html
Labels: GSSOC21, level0

#121 fixed the bugs in admin login and done some And Enhancements
  bookstore/templates/admin/login.html
Labels: GSSOC21, bug, level2

#122 Update technology stack in readme
  README.md
Labels: GSSOC21, level0

#124 Added dark mode to website
  bookstore/static/css/darkmode.css
  bookstore/static/js/darkmode.js
  bookstore/templates/admin/layout.html
  bookstore/templates/admin/login.html
  bookstore/templates/client/author_db.html
  bookstore/templates/client/contact2.html
  bookstore/templates/client/header.html
Labels: GSSOC21, enhancement, level3

#126 added dark mode to admin dashboard
  bookstore/templates/admin/contact_request.html
  bookstore/templates/admin/layout.html
  bookstore/templates/adminheader.html
Labels: GSSOC21, enhancement, level3

#130 fixed the bug in navbar toggle
  bookstore/templates/admin/layout.html
Labels: GSSOC21, bug, level2

#129 Security feature email alert
  bookstore/client/views.py
Labels: GSSOC21, enhancement, level3
